//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCentre
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arenda
    {
        public int ID_Arenda { get; set; }
        public Nullable<int> ID_Arendators { get; set; }
        public Nullable<int> ID_Sotrudnik { get; set; }
        public string Number_Pavilion { get; set; }
        public Nullable<int> ID_Shop { get; set; }
        public string Status_Arenda { get; set; }
        public Nullable<System.DateTime> Start_date { get; set; }
        public Nullable<System.DateTime> End_date { get; set; }
    
        public virtual Sotrudniki Sotrudniki { get; set; }
        public virtual Pavilions Pavilions { get; set; }
        public virtual Arendators Arendators { get; set; }
    }
}
