//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCentre
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop()
        {
            this.Pavilions = new HashSet<Pavilions>();
        }
    
        public int ID_Shop { get; set; }
        public string Name_Shop { get; set; }
        public string Status_Shop { get; set; }
        public Nullable<int> Count_pavillion { get; set; }
        public string City { get; set; }
        public Nullable<decimal> Price_Shop { get; set; }
        public Nullable<double> Coefficient_Shopping { get; set; }
        public Nullable<int> Count_floor { get; set; }
        public byte[] image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pavilions> Pavilions { get; set; }
    }
}
